spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/dbboy
    username: qcmr
    password: qcmr!@#

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true